# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{michael_hintbuble}
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Coroutine", "Tim Lowrimore", "John Dugan"]
  s.date = %q{2010-10-19}
  s.description = %q{Michael HintBuble allows you to generate hint bubbles and tooltips in Rails applications using the same syntax used for rendering templates.}
  s.email = %q{gems@coroutine.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".specification",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/michael_hintbuble/michael_hintbuble_generator.rb",
     "generators/michael_hintbuble/templates/error_bubble_pointer.png",
     "generators/michael_hintbuble/templates/help_bubble_pointer.png",
     "generators/michael_hintbuble/templates/michael_hintbuble.css",
     "generators/michael_hintbuble/templates/michael_hintbuble.js",
     "init.rb",
     "lib/generators/michael_hintbuble/michael_hintbuble_generator.rb",
     "lib/generators/michael_hintbuble/templates/error_bubble_pointer.png",
     "lib/generators/michael_hintbuble/templates/help_bubble_pointer.png",
     "lib/generators/michael_hintbuble/templates/michael_hintbuble.css",
     "lib/generators/michael_hintbuble/templates/michael_hintbuble.js",
     "lib/michael_hintbuble.rb",
     "lib/michael_hintbuble/helpers.rb",
     "michael_hintbuble.gemspec",
     "rails/init.rb",
     "test/michael_hintbuble/helpers_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/coroutine/michael_hintbuble}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Dead simple, beautiful hint bubbles for Rails.}
  s.test_files = [
    "test/michael_hintbuble/helpers_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.4"])
      s.add_development_dependency(%q<activesupport>, [">= 2.3.4"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.3.4"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.3.4"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
  end
end

